version: '3.9'

services:
  postgres:
   container_name: pg_db
   image: postgres:14-alpine
   environment:
      POSTGRES_DB: "users"
      POSTGRES_USER: "Timur"
      POSTGRES_PASSWORD: "1337"
   volumes:
      - ./postgres_data:/var/lib/postgresql/data/
   ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: timuryrtaev@yandex.ru
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
      